/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package json.parser;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.io.IOException;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.FileDescriptor;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintStream;
import java.io.UnsupportedEncodingException;
import java.nio.charset.StandardCharsets;

class ParserTest {
    final ByteArrayOutputStream baos = new ByteArrayOutputStream();
    final String utf8 = StandardCharsets.UTF_8.name();

    public void captureStdOut() {

        try {
            PrintStream ps = new PrintStream(baos, true, utf8);
            System.setOut(ps);
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }

    }

    @Test
    public void ParserParsesValidObject() {
        try {
            captureStdOut();

            Parser.parse(Paths.get("./src/test/resources/step1/valid.json"));
            String data = baos.toString(utf8);
            var a = 'a';
            assertNotNull(data);
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    @Test
    public void ParserErrorsOnInvalidObject() {
        try {
            Parser.parse(Paths.get("./src/test/resources/step1/invalid.json"));
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

}
